server:
  port: 8080   
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
 
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # 確保這一行存在
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:///${DB_NAME}  # 這裡應該是 ${DB_NAME} 環境變數，確保環境變數設置正確
    username: ${DB_USERNAME}  # 使用環境變數來設定資料庫用戶名
    password: ${DB_PASSWORD} # 使用環境變數來設定資料庫密碼
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: ${INSTANCE_NAME}  # 使用環境變數來設定實例連接名稱  # 使用環境變數來設定實例連接名稱        
     
